---
# file: tasks/repo.tml

- name: Obtaining percona public key
  apt_key: url=http://www.percona.com/downloads/RPM-GPG-KEY-percona
          state=present

- name: Download percona apt package
  get_url:
    url="https://repo.percona.com/apt/percona-release_0.1-4.{{ ansible_distribution_release }}_all.deb"
    dest="/tmp/percona-release_0.1-4.{{ ansible_distribution_release }}_all.deb"

- name: Install percona apt package
  apt: deb="/tmp/percona-release_0.1-4.{{ ansible_distribution_release }}_all.deb"
  sudo: true

- name: Update apt cache
  apt: update_cache=yes

